# Generated by Django 6.0.6 on 2026-06-08 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('suite', 'suite'), ('apartment', 'apartment'), ('basic', 'basic')], default='suite')),
                ('description', models.CharField(max_length=250)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=20)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('is_available', models.BooleanField(default=False)),
                ('amenities', models.JSONField(default=list, help_text='e.g., ["WiFi", "TV"]')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
